name: Build and Publish Docker Image to Docker Hub

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          
      - name: Build Image
        shell: bash
        run: docker build . -t ${{ secrets.DOCKER_USER }}/r-dev-image:latest
          
      - name: docker images
        shell: bash
        run: docker images
        
      - name: Optimize Docker Image
        shell: bash
        run: slim build --http-probe=false --pull ${{ secrets.DOCKER_USER }}/r-dev-image:latest
        
      - name: Push Docker Image to Dockerhub
        shell: bash
        run: docker push ${{ secrets.DOCKER_USER }}/r-dev-image.slim:latest
        
