name: Build and Optimize Docker Image

on:
  push:
    branches: ['main']
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Slimtoolkit
        shell: bash
        run: |
          curl -L -o ds.tar.gz https://downloads.dockerslim.com/releases/1.40.1/dist_linux.tar.gz
          sudo tar -xvf ds.tar.gz
          sudo mv dist_linux/docker-slim /usr/local/bin/
          sudo mv dist_linux/slim-sensor /usr/local/bin/
          sudo mv dist_linux/slim /usr/local/bin/
          
     # using slim to pull image directly from registry
      #- name: Optimize Docker image using SlimToolkit
       # run: |
        #  slim build --http-probe=false --pull ghcr.io/jamestripp/r-dev-image:main
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
      - name: Build Docker Image
        shell: bash
        run: docker build . -t ghcr.io/startrooper08/r-dev-image:latest
        
      - name: List Docker Images
        shell: bash
        run: docker images
        
      - name: Optimize Docker Image
        shell: bash
        run: slim build --http-probe=false --include-bin --pull ghcr.io/startrooper08/r-dev-image:latest
        
      - name: Push Docker Image to Github Container Registry
        shell: bash
        run: docker push ghcr.io/StarTrooper08/r-dev-image.slim:latest


