name: Build and Slim Docker Image

on:
  push:
    branches: ['main']
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Slimtoolkit
        run: |
          curl -L -o ds.tar.gz https://downloads.dockerslim.com/releases/1.40.1/dist_linux.tar.gz
          sudo tar -xvf ds.tar.gz
          sudo mv dist_linux/docker-slim /usr/local/bin/
          sudo mv dist_linux/slim-sensor /usr/local/bin/
          sudo mv dist_linux/slim /usr/local/bin/
          
     # using slim to pull image directly from registry
      #- name: Optimize Docker image using SlimToolkit
       # run: |
        #  slim build --http-probe=false --pull ghcr.io/jamestripp/r-dev-image:main
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GITHUB_TOKEN }}
         
      - name: Push optimized Docker image
        uses: docker/build-push-action@v4
        with:
         context: .
         push: true
         tags: ghcr.io/StarTooper08/r-dev-image:latest


